#=++

Copyright (C) 2021 ADSK

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.1-develop.

Abstract: This is an autogenerated Julia file in order to allow an easy
 use of RTTI

Interface version: 1.0.0

=#

module RTTI
using Libdl
if !@isdefined(Cbool)
	const Cbool = UInt8
end

struct ERTTIException <: Exception
	code::Int32
	message::String
end
Base.showerror(io::IO, e::ERTTIException) = print(io, "RTTIException ", e.code, e.message == "" ? "" : " : " * e.message)

@enum ErrorCodes::Int32 begin
	SUCCESS = 0
	NOTIMPLEMENTED = 1
	INVALIDPARAM = 2
	INVALIDCAST = 3
	BUFFERTOOSMALL = 4
	GENERICEXCEPTION = 5
	COULDNOTLOADLIBRARY = 6
	COULDNOTFINDLIBRARYEXPORT = 7
	INCOMPATIBLEBINARYVERSION = 8
end

const BINDING_VERSION_MAJOR = 1
const BINDING_VERSION_MINOR = 0
const BINDING_VERSION_MICRO = 0

abstract type AbstractRTTIClass end

mutable struct Wrapper
	lib::Ptr{Cvoid}
	funcs::Dict{Symbol, Ptr{Cvoid}}
	injected::Dict{String, Any}
end

function Wrapper(libraryName::Union{Nothing, AbstractString}=nothing; symbolLookupMethodAddress::Ptr{Cvoid}=C_NULL)
	lib = C_NULL
	funcs = Dict{Symbol, Ptr{Cvoid}}()
	injected = Dict{String, Any}()
	if libraryName === nothing && symbolLookupMethodAddress == C_NULL
		libraryName = joinpath(@__DIR__, "rtti")
	end
	if libraryName !== nothing
		libpath = String(libraryName) * "." * Libdl.dlext
		try
			lib = Libdl.dlopen(libpath)
		catch err
			throw(ERTTIException(Int32(COULDNOTLOADLIBRARY), string(err) * " | " * libpath))
		end
		w = Wrapper(lib, funcs, injected)
		_loadFunctionTable!(w)
	elseif symbolLookupMethodAddress != C_NULL
		w = Wrapper(lib, funcs, injected)
		_loadFunctionTableFromMethod!(w, symbolLookupMethodAddress)
	else
		throw(ERTTIException(Int32(COULDNOTLOADLIBRARY), "Invalid library configuration"))
	end
	_checkBinaryVersion(w)
	return w
end

function _loadFunctionTable!(w::Wrapper)
	w.funcs[:rtti_getversion] = Libdl.dlsym(w.lib, :rtti_getversion)
	w.funcs[:rtti_getlasterror] = Libdl.dlsym(w.lib, :rtti_getlasterror)
	w.funcs[:rtti_releaseinstance] = Libdl.dlsym(w.lib, :rtti_releaseinstance)
	w.funcs[:rtti_acquireinstance] = Libdl.dlsym(w.lib, :rtti_acquireinstance)
	w.funcs[:rtti_injectcomponent] = Libdl.dlsym(w.lib, :rtti_injectcomponent)
	w.funcs[:rtti_getsymbollookupmethod] = Libdl.dlsym(w.lib, :rtti_getsymbollookupmethod)
	w.funcs[:rtti_createzoo] = Libdl.dlsym(w.lib, :rtti_createzoo)
	w.funcs[:rtti_base_classtypeid] = Libdl.dlsym(w.lib, :rtti_base_classtypeid)
	w.funcs[:rtti_animal_name] = Libdl.dlsym(w.lib, :rtti_animal_name)
	w.funcs[:rtti_tiger_roar] = Libdl.dlsym(w.lib, :rtti_tiger_roar)
	w.funcs[:rtti_animaliterator_getnextanimal] = Libdl.dlsym(w.lib, :rtti_animaliterator_getnextanimal)
	w.funcs[:rtti_animaliterator_getnextoptinalanimal] = Libdl.dlsym(w.lib, :rtti_animaliterator_getnextoptinalanimal)
	w.funcs[:rtti_animaliterator_getnextmandatoryanimal] = Libdl.dlsym(w.lib, :rtti_animaliterator_getnextmandatoryanimal)
	w.funcs[:rtti_zoo_iterator] = Libdl.dlsym(w.lib, :rtti_zoo_iterator)
end

function _loadFunctionTableFromMethod!(w::Wrapper, symbolLookupMethodAddress::Ptr{Cvoid})
	for name in (
		"rtti_getversion",
		"rtti_getlasterror",
		"rtti_releaseinstance",
		"rtti_acquireinstance",
		"rtti_injectcomponent",
		"rtti_getsymbollookupmethod",
		"rtti_createzoo",
		"rtti_base_classtypeid",
		"rtti_animal_name",
		"rtti_tiger_roar",
		"rtti_animaliterator_getnextanimal",
		"rtti_animaliterator_getnextoptinalanimal",
		"rtti_animaliterator_getnextmandatoryanimal",
		"rtti_zoo_iterator",
	)
		addr = Ref{Ptr{Cvoid}}()
		err = ccall(symbolLookupMethodAddress, Int32, (Cstring, Ref{Ptr{Cvoid}}), name, addr)
		if err != 0
			throw(ERTTIException(Int32(COULDNOTLOADLIBRARY), string(err)))
		end
		w.funcs[Symbol(name)] = addr[]
	end
end

function _checkBinaryVersion(w::Wrapper)
	nMajor, nMinor, _ = GetVersion(w)
	if (nMajor != BINDING_VERSION_MAJOR) || (nMinor < BINDING_VERSION_MINOR)
		throw(ERTTIException(Int32(INCOMPATIBLEBINARYVERSION), ""))
	end
end

get_handle(obj::AbstractRTTIClass) = getfield(obj, :handle)
get_wrapper(obj::AbstractRTTIClass) = getfield(obj, :wrapper)

function _checkError(w::Wrapper, instance, errorCode::Int32)
	if errorCode != Int32(SUCCESS)
		if instance !== nothing
			if get_wrapper(instance) !== w
				throw(ERTTIException(Int32(INVALIDCAST), "invalid wrapper call"))
			end
		end
		message, _ = GetLastError(w, instance)
		throw(ERTTIException(errorCode, message))
	end
end

function _attach_finalizer(obj)
	finalizer(obj) do o
		try
			ReleaseInstance(get_wrapper(o), o)
		catch
		end
	end
	return obj
end

function _make_object(::Type{T}, handle::Ptr{Cvoid}, w::Wrapper) where {T<:AbstractRTTIClass}
	obj = T(handle, w)
	return _attach_finalizer(obj)
end

# Polymorphic factory
function _polymorphicFactory(w::Wrapper, handle::Ptr{Cvoid})
	handle == C_NULL && return nothing
	classTypeId = Ref{UInt64}(0)
	err = ccall(w.funcs[:rtti_base_classtypeid], Int32, (Ptr{Cvoid}, Ref{UInt64}), handle, classTypeId)
	_checkError(w, nothing, err)
	return _objectById(w, classTypeId[], handle)
end

function _objectById(w::Wrapper, classTypeId::UInt64, handle::Ptr{Cvoid})
	if classTypeId == 0x1549AD28813DAE05
		return _make_object(Base, handle, w)
	elseif classTypeId == 0x8B40467DA6D327AF
		return _make_object(Animal, handle, w)
	elseif classTypeId == 0xBC9D5FA7750C1020
		return _make_object(Mammal, handle, w)
	elseif classTypeId == 0x6756AA8EA5802EC3
		return _make_object(Reptile, handle, w)
	elseif classTypeId == 0x9751971BD2C2D958
		return _make_object(Giraffe, handle, w)
	elseif classTypeId == 0x08D007E7B5F7BAF4
		return _make_object(Tiger, handle, w)
	elseif classTypeId == 0x5F6826EF909803B2
		return _make_object(Snake, handle, w)
	elseif classTypeId == 0x8E551B208A2E8321
		return _make_object(Turtle, handle, w)
	elseif classTypeId == 0xF1917FE6BBE77831
		return _make_object(AnimalIterator, handle, w)
	elseif classTypeId == 0x2262ABE80A5E7878
		return _make_object(Zoo, handle, w)
	else
		return nothing
	end
end

mutable struct Base <: AbstractRTTIClass
	handle::Ptr{Cvoid}
	wrapper::Wrapper
end

mutable struct Animal <: AbstractRTTIClass
	handle::Ptr{Cvoid}
	wrapper::Wrapper
end

mutable struct Mammal <: AbstractRTTIClass
	handle::Ptr{Cvoid}
	wrapper::Wrapper
end

mutable struct Reptile <: AbstractRTTIClass
	handle::Ptr{Cvoid}
	wrapper::Wrapper
end

mutable struct Giraffe <: AbstractRTTIClass
	handle::Ptr{Cvoid}
	wrapper::Wrapper
end

mutable struct Tiger <: AbstractRTTIClass
	handle::Ptr{Cvoid}
	wrapper::Wrapper
end

mutable struct Snake <: AbstractRTTIClass
	handle::Ptr{Cvoid}
	wrapper::Wrapper
end

mutable struct Turtle <: AbstractRTTIClass
	handle::Ptr{Cvoid}
	wrapper::Wrapper
end

mutable struct AnimalIterator <: AbstractRTTIClass
	handle::Ptr{Cvoid}
	wrapper::Wrapper
end

mutable struct Zoo <: AbstractRTTIClass
	handle::Ptr{Cvoid}
	wrapper::Wrapper
end

function GetVersion(w::Wrapper)
	pMajor = Ref{UInt32}()
	pMinor = Ref{UInt32}()
	pMicro = Ref{UInt32}()
	err = ccall(w.funcs[:rtti_getversion], Int32, (Ref{UInt32}, Ref{UInt32}, Ref{UInt32}), pMajor, pMinor, pMicro)
	_checkError(w, nothing, err)
	return pMajor[], pMinor[], pMicro[]
end

function GetLastError(w::Wrapper, Instance::Base)
	nErrorMessageBufferSize = UInt64(0)
	nErrorMessageNeeded = Ref{UInt64}(0)
	pErrorMessageBuffer = Ptr{Cchar}(C_NULL)
	pHasError = Ref{Cbool}()
	err = ccall(w.funcs[:rtti_getlasterror], Int32, (Ptr{Cvoid}, UInt64, Ref{UInt64}, Ptr{Cchar}, Ref{Cbool}), Instance.handle, nErrorMessageBufferSize, nErrorMessageNeeded, pErrorMessageBuffer, pHasError)
	_checkError(w, nothing, err)
	pErrorMessageBuffer = Vector{UInt8}(undef, Int(nErrorMessageNeeded[]))
	nErrorMessageBufferSize = UInt64(length(pErrorMessageBuffer))
	pErrorMessageBuffer_ptr = pointer(pErrorMessageBuffer)
	GC.@preserve pErrorMessageBuffer begin
		err = ccall(w.funcs[:rtti_getlasterror], Int32, (Ptr{Cvoid}, UInt64, Ref{UInt64}, Ptr{Cchar}, Ref{Cbool}), Instance.handle, nErrorMessageBufferSize, nErrorMessageNeeded, pErrorMessageBuffer_ptr, pHasError)
	end
	_checkError(w, nothing, err)
	return unsafe_string(pErrorMessageBuffer_ptr), pHasError[] != 0
end

function ReleaseInstance(w::Wrapper, Instance::Base)
	err = ccall(w.funcs[:rtti_releaseinstance], Int32, (Ptr{Cvoid},), Instance.handle)
	_checkError(w, nothing, err)
end

function AcquireInstance(w::Wrapper, Instance::Base)
	err = ccall(w.funcs[:rtti_acquireinstance], Int32, (Ptr{Cvoid},), Instance.handle)
	_checkError(w, nothing, err)
end

function InjectComponent(w::Wrapper, NameSpace::AbstractString, SymbolAddressMethod::Ptr{Cvoid})
	GC.@preserve NameSpace begin
		err = ccall(w.funcs[:rtti_injectcomponent], Int32, (Cstring, Ptr{Cvoid}), NameSpace, SymbolAddressMethod)
	end
	_checkError(w, nothing, err)
end

function GetSymbolLookupMethod(w::Wrapper)
	pSymbolLookupMethod = Ref{Ptr{Cvoid}}()
	err = ccall(w.funcs[:rtti_getsymbollookupmethod], Int32, (Ref{Ptr{Cvoid}},), pSymbolLookupMethod)
	_checkError(w, nothing, err)
	return pSymbolLookupMethod[]
end

function CreateZoo(w::Wrapper)
	pInstance = Ref{Ptr{Cvoid}}(C_NULL)
	err = ccall(w.funcs[:rtti_createzoo], Int32, (Ref{Ptr{Cvoid}},), pInstance)
	_checkError(w, nothing, err)
	return _polymorphicFactory(w, pInstance[])
end

function ClassTypeId(self::Base)
	pClassTypeId = Ref{UInt64}()
	err = ccall(self.wrapper.funcs[:rtti_base_classtypeid], Int32, (Ptr{Cvoid}, Ref{UInt64}), self.handle, pClassTypeId)
	_checkError(self.wrapper, self, err)
	return pClassTypeId[]
end

function Name(self::Animal)
	nResultBufferSize = UInt64(0)
	nResultNeeded = Ref{UInt64}(0)
	pResultBuffer = Ptr{Cchar}(C_NULL)
	err = ccall(self.wrapper.funcs[:rtti_animal_name], Int32, (Ptr{Cvoid}, UInt64, Ref{UInt64}, Ptr{Cchar}), self.handle, nResultBufferSize, nResultNeeded, pResultBuffer)
	_checkError(self.wrapper, self, err)
	pResultBuffer = Vector{UInt8}(undef, Int(nResultNeeded[]))
	nResultBufferSize = UInt64(length(pResultBuffer))
	pResultBuffer_ptr = pointer(pResultBuffer)
	GC.@preserve pResultBuffer begin
		err = ccall(self.wrapper.funcs[:rtti_animal_name], Int32, (Ptr{Cvoid}, UInt64, Ref{UInt64}, Ptr{Cchar}), self.handle, nResultBufferSize, nResultNeeded, pResultBuffer_ptr)
	end
	_checkError(self.wrapper, self, err)
	return unsafe_string(pResultBuffer_ptr)
end

function ClassTypeId(self::Animal)
	return ClassTypeId(Base(self.handle, self.wrapper))
end

function Name(self::Mammal)
	return Name(Animal(self.handle, self.wrapper))
end

function ClassTypeId(self::Mammal)
	return ClassTypeId(Base(self.handle, self.wrapper))
end

function Name(self::Reptile)
	return Name(Animal(self.handle, self.wrapper))
end

function ClassTypeId(self::Reptile)
	return ClassTypeId(Base(self.handle, self.wrapper))
end

function Name(self::Giraffe)
	return Name(Animal(self.handle, self.wrapper))
end

function ClassTypeId(self::Giraffe)
	return ClassTypeId(Base(self.handle, self.wrapper))
end

function Roar(self::Tiger)
	err = ccall(self.wrapper.funcs[:rtti_tiger_roar], Int32, (Ptr{Cvoid},), self.handle)
	_checkError(self.wrapper, self, err)
end

function Name(self::Tiger)
	return Name(Animal(self.handle, self.wrapper))
end

function ClassTypeId(self::Tiger)
	return ClassTypeId(Base(self.handle, self.wrapper))
end

function Name(self::Snake)
	return Name(Animal(self.handle, self.wrapper))
end

function ClassTypeId(self::Snake)
	return ClassTypeId(Base(self.handle, self.wrapper))
end

function Name(self::Turtle)
	return Name(Animal(self.handle, self.wrapper))
end

function ClassTypeId(self::Turtle)
	return ClassTypeId(Base(self.handle, self.wrapper))
end

function GetNextAnimal(self::AnimalIterator)
	pAnimal = Ref{Ptr{Cvoid}}(C_NULL)
	err = ccall(self.wrapper.funcs[:rtti_animaliterator_getnextanimal], Int32, (Ptr{Cvoid}, Ref{Ptr{Cvoid}}), self.handle, pAnimal)
	_checkError(self.wrapper, self, err)
	return _polymorphicFactory(self.wrapper, pAnimal[])
end

function GetNextOptinalAnimal(self::AnimalIterator, Animal::Union{Animal, Nothing}=nothing)
	pAnimal = Ref{Ptr{Cvoid}}(Animal === nothing ? C_NULL : Animal.handle)
	pError = Ref{Cbool}()
	err = ccall(self.wrapper.funcs[:rtti_animaliterator_getnextoptinalanimal], Int32, (Ptr{Cvoid}, Ref{Ptr{Cvoid}}, Ref{Cbool}), self.handle, pAnimal, pError)
	_checkError(self.wrapper, self, err)
	return _polymorphicFactory(self.wrapper, pAnimal[]), pError[] != 0
end

function GetNextMandatoryAnimal(self::AnimalIterator, Animal::Union{Animal, Nothing}=nothing)
	pAnimal = Ref{Ptr{Cvoid}}(Animal === nothing ? C_NULL : Animal.handle)
	pError = Ref{Cbool}()
	err = ccall(self.wrapper.funcs[:rtti_animaliterator_getnextmandatoryanimal], Int32, (Ptr{Cvoid}, Ref{Ptr{Cvoid}}, Ref{Cbool}), self.handle, pAnimal, pError)
	_checkError(self.wrapper, self, err)
	return _polymorphicFactory(self.wrapper, pAnimal[]), pError[] != 0
end

function ClassTypeId(self::AnimalIterator)
	return ClassTypeId(Base(self.handle, self.wrapper))
end

function Iterator(self::Zoo)
	pIterator = Ref{Ptr{Cvoid}}(C_NULL)
	err = ccall(self.wrapper.funcs[:rtti_zoo_iterator], Int32, (Ptr{Cvoid}, Ref{Ptr{Cvoid}}), self.handle, pIterator)
	_checkError(self.wrapper, self, err)
	return _polymorphicFactory(self.wrapper, pIterator[])
end

function ClassTypeId(self::Zoo)
	return ClassTypeId(Base(self.handle, self.wrapper))
end

end # module RTTI
