#=++

Copyright (C) 2021 ADSK

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.1-develop.

Abstract: This is an autogenerated Julia application that demonstrates the
 usage of the Julia bindings of RTTI

Interface version: 1.0.0

=#

include(joinpath(@__DIR__, "..", "..", "Bindings", "Julia", "RTTI.jl"))
using .RTTI

println("Running RTTI Julia Example...")
wrapper = RTTI.Wrapper("rtti")
major, minor, micro = RTTI.GetVersion(wrapper)
println("RTTI version: " * string(major) * "." * string(minor) * "." * string(micro))

zoo = RTTI.CreateZoo(wrapper)
it = RTTI.Iterator(zoo)
while true
	animal = RTTI.GetNextAnimal(it)
	animal === nothing && break
	println("Animal name: " * RTTI.Name(animal))
	if animal isa RTTI.Tiger
		RTTI.Roar(animal)
	end
end
