/*++

Copyright (C) 2026 Autodesk Inc.

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

--*/

//////////////////////////////////////////////////////////////////////////////////////////////////////
// buildbindingrust.go
// functions to generate dynamic Rust bindings of a library's API in form of explicitly loaded
// function handles.
//////////////////////////////////////////////////////////////////////////////////////////////////////

package main

import (
	"fmt"
	"log"
	"os"
	"path"
	"strings"
)

// Store the rust file path
var rustBindingFile = ""

// BuildBindingRustDynamic builds dynamic Rust bindings of a library's API in form of explicitly loaded
// function handles.
func BuildBindingRustDynamic(componentdefinition ComponentDefinition, outputFolder string, outputFolderExample string, indentString string) error {
	forceRecreation := false

	libraryname := componentdefinition.LibraryName

	srcFolder := path.Join(outputFolder, "src")
	err := os.MkdirAll(srcFolder, os.ModePerm)
	if err != nil {
		return err
	}

	DynamicRustImpl := path.Join(srcFolder, "lib.rs")
	rustBindingFile = DynamicRustImpl
	log.Printf("Creating \"%s\"", DynamicRustImpl)
	dynrustfile, err := CreateLanguageFile(DynamicRustImpl, indentString)
	if err != nil {
		return err
	}

	dynrustfile.WriteCLicenseHeader(componentdefinition,
		fmt.Sprintf("This is an autogenerated Rust file in order to allow an easy\n use of %s", libraryname),
		true)

	err = buildDynamicRustImplementation(componentdefinition, dynrustfile)
	if err != nil {
		return err
	}

	cargoFile := path.Join(outputFolder, "Cargo.toml")
	if forceRecreation || !FileExists(cargoFile) {
		log.Printf("Creating \"%s\"", cargoFile)
		cargofile, err := CreateLanguageFile(cargoFile, indentString)
		if err != nil {
			return err
		}
		err = buildDynamicRustCargo(componentdefinition, cargofile)
		if err != nil {
			return err
		}
	}

	if len(outputFolderExample) > 0 {
		DynamicRustExample := path.Join(outputFolderExample, "version.rs")
		if forceRecreation || !FileExists(DynamicRustExample) {
			log.Printf("Creating \"%s\"", DynamicRustExample)
			dynrustexamplefile, err := CreateLanguageFile(DynamicRustExample, indentString)
			if err != nil {
				return err
			}
			dynrustexamplefile.WriteCLicenseHeader(componentdefinition,
				fmt.Sprintf("This is an autogenerated Rust application that demonstrates the\n usage of the Rust bindings of %s", libraryname),
				true)
			err = buildDynamicRustExample(componentdefinition, dynrustexamplefile)
			if err != nil {
				return err
			}
		} else {
			log.Printf("Omitting recreation of Rust example \"%s\"", DynamicRustExample)
		}
	}

	return nil
}

func buildDynamicRustCargo(componentdefinition ComponentDefinition, w LanguageWriter) error {
	crateName := strings.ToLower(componentdefinition.NameSpace)
	w.Writeln("[package]")
	w.Writeln("name = \"%s\"", crateName)
	w.Writeln("version = \"%s\"", componentdefinition.Version)
	w.Writeln("edition = \"2021\"")
	return nil
}

func buildDynamicRustImplementation(componentdefinition ComponentDefinition, w LanguageWriter) error {
	NameSpace := componentdefinition.NameSpace
	BaseName := componentdefinition.BaseName

	w.Writeln("use std::ffi::{CStr, CString};")
	w.Writeln("use std::os::raw::{c_char, c_void};")
	w.Writeln("use std::mem;")
	w.Writeln("use std::ptr;")
	w.Writeln("")
	w.Writeln("#[cfg(unix)]")
	w.Writeln("mod dynlib {")
	w.Writeln("    use super::*;")
	w.Writeln("    type DynResult<T> = std::result::Result<T, String>;")
	w.Writeln("    #[link(name = \"dl\")]")
	w.Writeln("    extern \"C\" {")
		w.Writeln("        fn dlopen(filename: *const c_char, flag: i32) -> *mut c_void;")
		w.Writeln("        fn dlsym(handle: *mut c_void, symbol: *const c_char) -> *mut c_void;")
		w.Writeln("        fn dlclose(handle: *mut c_void) -> i32;")
		w.Writeln("        fn dlerror() -> *const c_char;")
	w.Writeln("    }")
	w.Writeln("    const RTLD_NOW: i32 = 2;")
	w.Writeln("    pub struct Library { handle: *mut c_void }")
	w.Writeln("    impl Library {")
	w.Writeln("        pub unsafe fn new(path: &str) -> DynResult<Self> {")
	w.Writeln("            let cpath = CString::new(path).map_err(|_| \"library path contains NUL\".to_string())?;")
	w.Writeln("            let handle = dlopen(cpath.as_ptr(), RTLD_NOW);")
	w.Writeln("            if handle.is_null() { return Err(last_error()); }")
	w.Writeln("            Ok(Self { handle })")
	w.Writeln("        }")
	w.Writeln("        pub unsafe fn get(&self, symbol: &str) -> DynResult<*mut c_void> {")
	w.Writeln("            let csym = CString::new(symbol).map_err(|_| \"symbol contains NUL\".to_string())?;")
	w.Writeln("            let sym = dlsym(self.handle, csym.as_ptr());")
	w.Writeln("            if sym.is_null() { return Err(last_error()); }")
	w.Writeln("            Ok(sym)")
	w.Writeln("        }")
	w.Writeln("    }")
	w.Writeln("    impl Drop for Library {")
	w.Writeln("        fn drop(&mut self) {")
	w.Writeln("            unsafe {")
	w.Writeln("                if !self.handle.is_null() {")
	w.Writeln("                    dlclose(self.handle);")
	w.Writeln("                }")
	w.Writeln("            }")
	w.Writeln("        }")
	w.Writeln("    }")
	w.Writeln("    fn last_error() -> String {")
	w.Writeln("        unsafe {")
	w.Writeln("            let err = dlerror();")
	w.Writeln("            if err.is_null() {")
	w.Writeln("                \"unknown dlerror\".to_string()")
	w.Writeln("            } else {")
	w.Writeln("                CStr::from_ptr(err).to_string_lossy().into_owned()")
	w.Writeln("            }")
	w.Writeln("        }")
	w.Writeln("    }")
	w.Writeln("}")
	w.Writeln("")
	w.Writeln("#[cfg(windows)]")
	w.Writeln("mod dynlib {")
	w.Writeln("    use super::*;")
	w.Writeln("    type DynResult<T> = std::result::Result<T, String>;")
	w.Writeln("    type HMODULE = *mut c_void;")
	w.Writeln("    #[link(name = \"kernel32\")]")
	w.Writeln("    extern \"system\" {")
		w.Writeln("        fn LoadLibraryA(lpLibFileName: *const c_char) -> HMODULE;")
		w.Writeln("        fn GetProcAddress(hModule: HMODULE, lpProcName: *const c_char) -> *mut c_void;")
		w.Writeln("        fn FreeLibrary(hModule: HMODULE) -> i32;")
		w.Writeln("        fn GetLastError() -> u32;")
	w.Writeln("    }")
	w.Writeln("    pub struct Library { handle: HMODULE }")
	w.Writeln("    impl Library {")
	w.Writeln("        pub unsafe fn new(path: &str) -> DynResult<Self> {")
	w.Writeln("            let cpath = CString::new(path).map_err(|_| \"library path contains NUL\".to_string())?;")
	w.Writeln("            let handle = LoadLibraryA(cpath.as_ptr());")
	w.Writeln("            if handle.is_null() { return Err(last_error()); }")
	w.Writeln("            Ok(Self { handle })")
	w.Writeln("        }")
	w.Writeln("        pub unsafe fn get(&self, symbol: &str) -> DynResult<*mut c_void> {")
	w.Writeln("            let csym = CString::new(symbol).map_err(|_| \"symbol contains NUL\".to_string())?;")
	w.Writeln("            let sym = GetProcAddress(self.handle, csym.as_ptr());")
	w.Writeln("            if sym.is_null() { return Err(last_error()); }")
	w.Writeln("            Ok(sym)")
	w.Writeln("        }")
	w.Writeln("    }")
	w.Writeln("    impl Drop for Library {")
	w.Writeln("        fn drop(&mut self) {")
	w.Writeln("            unsafe {")
	w.Writeln("                if !self.handle.is_null() {")
	w.Writeln("                    FreeLibrary(self.handle);")
	w.Writeln("                }")
	w.Writeln("            }")
	w.Writeln("        }")
	w.Writeln("    }")
	w.Writeln("    fn last_error() -> String {")
	w.Writeln("        let code = unsafe { GetLastError() };")
	w.Writeln("        format!(\"Win32 error {}\", code)")
	w.Writeln("    }")
	w.Writeln("}")
	w.Writeln("")
	w.Writeln("use dynlib::Library;")
	w.Writeln("")

	w.Writeln("pub type CBool = u8;")
	w.Writeln("")

	w.Writeln("#[repr(i32)]")
	w.Writeln("#[derive(Debug, Copy, Clone, PartialEq, Eq)]")
	w.Writeln("pub enum ErrorCodes {")
	w.Writeln("    SUCCESS = 0,")
	for _, errorDef := range componentdefinition.Errors.Errors {
		w.Writeln("    %s = %d,", errorDef.Name, errorDef.Code)
	}
	w.Writeln("}")
	w.Writeln("")

	w.Writeln("#[derive(Debug)]")
	w.Writeln("pub struct %sError {", NameSpace)
	w.Writeln("    pub code: i32,")
	w.Writeln("    pub message: String,")
	w.Writeln("}")
	w.Writeln("impl %sError {", NameSpace)
	w.Writeln("    fn new(code: i32, message: String) -> Self {")
	w.Writeln("        Self { code, message }")
	w.Writeln("    }")
	w.Writeln("}")
	w.Writeln("")
	w.Writeln("pub type Result<T> = std::result::Result<T, %sError>;", NameSpace)
	w.Writeln("")

	if len(componentdefinition.Enums) > 0 {
		w.Writeln("// Enums")
		for _, enum := range componentdefinition.Enums {
			w.Writeln("#[repr(i32)]")
			w.Writeln("#[derive(Debug, Copy, Clone, PartialEq, Eq)]")
			w.Writeln("pub enum e%s {", enum.Name)
			for _, option := range enum.Options {
				w.Writeln("    %s = %d,", option.Name, option.Value)
			}
			w.Writeln("}")
		}
		w.Writeln("")
	}

	if len(componentdefinition.Structs) > 0 {
		w.Writeln("// Structs")
		for _, s := range componentdefinition.Structs {
			w.Writeln("#[repr(C)]")
			w.Writeln("#[derive(Debug, Copy, Clone)]")
			w.Writeln("pub struct s%s {", s.Name)
			for _, m := range s.Members {
				memberType, err := rustStructMemberType(m, componentdefinition)
				if err != nil {
					return err
				}
				w.Writeln("    pub %s: %s,", m.Name, memberType)
			}
			w.Writeln("}")
		}
		w.Writeln("")
	}

	// Handle types for classes
	for _, class := range componentdefinition.Classes {
		w.Writeln("pub type %s_%s = *mut c_void;", NameSpace, class.ClassName)
	}
	w.Writeln("")

	// Function types
	if len(componentdefinition.Functions) > 0 {
		w.Writeln("// Function types")
		for _, functiontype := range componentdefinition.Functions {
			params := []string{}
			for _, p := range functiontype.Params {
				paramType, err := rustScalarType(p.ParamType, componentdefinition, p.ParamClass)
				if err != nil {
					return err
				}
				params = append(params, paramType)
			}
			w.Writeln("pub type %s%s = unsafe extern \"C\" fn(%s);", NameSpace, functiontype.FunctionName, strings.Join(params, ", "))
		}
		w.Writeln("")
	}

	// API function table
	w.Writeln("pub struct Api {")
	for _, method := range componentdefinition.Global.Methods {
		exportName := GetCExportName(NameSpace, "Wrapper", method, true)
		sig, err := rustMethodSignature(method, NameSpace, componentdefinition, true, "")
		if err != nil {
			return err
		}
		w.Writeln("    pub %s: %s,", exportName, sig)
	}
	for _, class := range componentdefinition.Classes {
		for _, method := range class.Methods {
			exportName := GetCExportName(NameSpace, class.ClassName, method, false)
			sig, err := rustMethodSignature(method, NameSpace, componentdefinition, false, class.ClassName)
			if err != nil {
				return err
			}
			w.Writeln("    pub %s: %s,", exportName, sig)
		}
	}
	w.Writeln("}")
	w.Writeln("")

	w.Writeln("impl Api {")
	w.Writeln("    unsafe fn load(lib: &Library) -> Result<Self> {")
	w.Writeln("        unsafe fn load_symbol(lib: &Library, name: &str) -> Result<*mut c_void> {")
	w.Writeln("            lib.get(name)")
	w.Writeln("                .map_err(|e| %sError::new(ErrorCodes::COULDNOTFINDLIBRARYEXPORT as i32, e))", NameSpace)
	w.Writeln("        }")
	w.Writeln("        Ok(Self {")
	for _, method := range componentdefinition.Global.Methods {
		exportName := GetCExportName(NameSpace, "Wrapper", method, true)
		w.Writeln("            %s: mem::transmute(load_symbol(lib, \"%s\")?) ,", exportName, exportName)
	}
	for _, class := range componentdefinition.Classes {
		for _, method := range class.Methods {
			exportName := GetCExportName(NameSpace, class.ClassName, method, false)
			w.Writeln("            %s: mem::transmute(load_symbol(lib, \"%s\")?) ,", exportName, exportName)
		}
	}
	w.Writeln("        })")
	w.Writeln("    }")
	w.Writeln("}")
	w.Writeln("")

	// Wrapper
	w.Writeln("pub struct Wrapper {")
	w.Writeln("    _lib: Library,")
	w.Writeln("    api: Api,")
	w.Writeln("}")
	w.Writeln("")

	w.Writeln("impl Wrapper {")
	w.Writeln("    pub fn new(library_name: Option<&str>) -> Result<Self> {")
	w.Writeln("        let base = library_name.unwrap_or(\"%s\");", BaseName)
	w.Writeln("        let libpath = if cfg!(target_os = \"windows\") {")
	w.Writeln("            format!(\"{}.dll\", base)")
	w.Writeln("        } else if cfg!(target_os = \"macos\") {")
	w.Writeln("            format!(\"{}.dylib\", base)")
	w.Writeln("        } else {")
	w.Writeln("            format!(\"{}.so\", base)")
	w.Writeln("        };")
	w.Writeln("        let lib = unsafe { Library::new(&libpath) }")
	w.Writeln("            .map_err(|e| %sError::new(ErrorCodes::COULDNOTLOADLIBRARY as i32, e))?;", NameSpace)
	w.Writeln("        let api = unsafe { Api::load(&lib) }")
	w.Writeln("            .map_err(|e| %sError::new(ErrorCodes::COULDNOTFINDLIBRARYEXPORT as i32, e.message))?;", NameSpace)
	w.Writeln("        Ok(Self { _lib: lib, api })")
	w.Writeln("    }")
	w.Writeln("")
	w.Writeln("    pub fn api(&self) -> &Api {")
	w.Writeln("        &self.api")
	w.Writeln("    }")
	w.Writeln("")

	// GetLastError helper (raw)
	if method, ok := findGlobalMethod(componentdefinition, "GetLastError"); ok {
		exportName := GetCExportName(NameSpace, "Wrapper", method, true)
		w.Writeln("    fn get_last_error_message(&self, instance: *mut c_void) -> String {")
		w.Writeln("        let mut needed: u32 = 0;")
		w.Writeln("        let mut has_error: CBool = 0;")
		w.Writeln("        let err = unsafe { (self.api.%s)(instance, 0, &mut needed, ptr::null_mut(), &mut has_error) };", exportName)
		w.Writeln("        if err != 0 || has_error == 0 || needed == 0 {")
		w.Writeln("            return String::new();")
		w.Writeln("        }")
		w.Writeln("        let mut buffer = vec![0u8; needed as usize];")
		w.Writeln("        let err = unsafe { (self.api.%s)(instance, buffer.len() as u32, &mut needed, buffer.as_mut_ptr() as *mut c_char, &mut has_error) };", exportName)
		w.Writeln("        if err != 0 || has_error == 0 {")
		w.Writeln("            return String::new();")
		w.Writeln("        }")
		w.Writeln("        unsafe { CStr::from_ptr(buffer.as_ptr() as *const c_char).to_string_lossy().into_owned() }")
		w.Writeln("    }")
	} else {
		w.Writeln("    fn get_last_error_message(&self, _instance: *mut c_void) -> String {")
		w.Writeln("        String::new()")
		w.Writeln("    }")
	}
	w.Writeln("")

	w.Writeln("    fn check_err(&self, instance: *mut c_void, err: i32) -> Result<()> {")
	w.Writeln("        if err == 0 {")
	w.Writeln("            return Ok(());")
	w.Writeln("        }")
	w.Writeln("        let msg = self.get_last_error_message(instance);")
	w.Writeln("        Err(%sError::new(err, msg))", NameSpace)
	w.Writeln("    }")
	w.Writeln("")

	// Minimal safe wrappers (version info)
	if method, ok := findGlobalMethod(componentdefinition, "GetLibraryVersion"); ok {
		exportName := GetCExportName(NameSpace, "Wrapper", method, true)
		w.Writeln("    pub fn GetLibraryVersion(&self) -> Result<(u32, u32, u32)> {")
		w.Writeln("        let mut major: u32 = 0;")
		w.Writeln("        let mut minor: u32 = 0;")
		w.Writeln("        let mut micro: u32 = 0;")
		w.Writeln("        let err = unsafe { (self.api.%s)(&mut major, &mut minor, &mut micro) };", exportName)
		w.Writeln("        self.check_err(ptr::null_mut(), err)?;")
		w.Writeln("        Ok((major, minor, micro))")
		w.Writeln("    }")
		w.Writeln("")
	}

	if method, ok := findGlobalMethod(componentdefinition, "GetVersion"); ok {
		exportName := GetCExportName(NameSpace, "Wrapper", method, true)
		w.Writeln("    pub fn GetVersion(&self) -> Result<(u32, u32, u32)> {")
		w.Writeln("        let mut major: u32 = 0;")
		w.Writeln("        let mut minor: u32 = 0;")
		w.Writeln("        let mut micro: u32 = 0;")
		w.Writeln("        let err = unsafe { (self.api.%s)(&mut major, &mut minor, &mut micro) };", exportName)
		w.Writeln("        self.check_err(ptr::null_mut(), err)?;")
		w.Writeln("        Ok((major, minor, micro))")
		w.Writeln("    }")
		w.Writeln("")
	}

	if method, ok := findGlobalMethod(componentdefinition, "GetPrereleaseInformation"); ok {
		exportName := GetCExportName(NameSpace, "Wrapper", method, true)
		w.Writeln("    pub fn GetPrereleaseInformation(&self) -> Result<(bool, String)> {")
		w.Writeln("        let mut has_info: CBool = 0;")
		w.Writeln("        let mut needed: u32 = 0;")
		w.Writeln("        let err = unsafe { (self.api.%s)(&mut has_info, 0, &mut needed, ptr::null_mut()) };", exportName)
		w.Writeln("        self.check_err(ptr::null_mut(), err)?;")
		w.Writeln("        if needed == 0 {")
			w.Writeln("            return Ok((has_info != 0, String::new()));")
		w.Writeln("        }")
		w.Writeln("        let mut buffer = vec![0u8; needed as usize];")
		w.Writeln("        let err = unsafe { (self.api.%s)(&mut has_info, buffer.len() as u32, &mut needed, buffer.as_mut_ptr() as *mut c_char) };", exportName)
		w.Writeln("        self.check_err(ptr::null_mut(), err)?;")
		w.Writeln("        let msg = unsafe { CStr::from_ptr(buffer.as_ptr() as *const c_char).to_string_lossy().into_owned() };")
		w.Writeln("        Ok((has_info != 0, msg))")
		w.Writeln("    }")
		w.Writeln("")
	}

	if method, ok := findGlobalMethod(componentdefinition, "GetBuildInformation"); ok {
		exportName := GetCExportName(NameSpace, "Wrapper", method, true)
		w.Writeln("    pub fn GetBuildInformation(&self) -> Result<(bool, String)> {")
		w.Writeln("        let mut has_info: CBool = 0;")
		w.Writeln("        let mut needed: u32 = 0;")
		w.Writeln("        let err = unsafe { (self.api.%s)(&mut has_info, 0, &mut needed, ptr::null_mut()) };", exportName)
		w.Writeln("        self.check_err(ptr::null_mut(), err)?;")
		w.Writeln("        if needed == 0 {")
			w.Writeln("            return Ok((has_info != 0, String::new()));")
		w.Writeln("        }")
		w.Writeln("        let mut buffer = vec![0u8; needed as usize];")
		w.Writeln("        let err = unsafe { (self.api.%s)(&mut has_info, buffer.len() as u32, &mut needed, buffer.as_mut_ptr() as *mut c_char) };", exportName)
		w.Writeln("        self.check_err(ptr::null_mut(), err)?;")
		w.Writeln("        let msg = unsafe { CStr::from_ptr(buffer.as_ptr() as *const c_char).to_string_lossy().into_owned() };")
		w.Writeln("        Ok((has_info != 0, msg))")
		w.Writeln("    }")
		w.Writeln("")
	}
	w.Writeln("}")

	return nil
}

func buildDynamicRustExample(componentdefinition ComponentDefinition, w LanguageWriter) error {
	NameSpace := componentdefinition.NameSpace
	crateName := strings.ToLower(NameSpace)
	versionMethod := ""
	if _, ok := findGlobalMethod(componentdefinition, "GetLibraryVersion"); ok {
		versionMethod = "GetLibraryVersion"
	} else if _, ok := findGlobalMethod(componentdefinition, "GetVersion"); ok {
		versionMethod = "GetVersion"
	}
	w.Writeln("use %s::Wrapper;", crateName)
	w.Writeln("")
	w.Writeln("fn main() {")
	w.Writeln("    let wrapper = Wrapper::new(None).expect(\"failed to load library\");")
	if versionMethod != "" {
		w.Writeln("    let (major, minor, micro) = wrapper.%s().expect(\"version\");", versionMethod)
		w.Writeln("    print!(\"%s version = {}.{}.{}\", major, minor, micro);", NameSpace)
	} else {
		w.Writeln("    print!(\"%s wrapper loaded\");", NameSpace)
	}
	if _, ok := findGlobalMethod(componentdefinition, "GetPrereleaseInformation"); ok {
		w.Writeln("    if let Ok((has_pre, pre)) = wrapper.GetPrereleaseInformation() {")
		w.Writeln("        if has_pre { print!(\"-{}\", pre); }")
		w.Writeln("    }")
	}
	if _, ok := findGlobalMethod(componentdefinition, "GetBuildInformation"); ok {
		w.Writeln("    if let Ok((has_build, build)) = wrapper.GetBuildInformation() {")
		w.Writeln("        if has_build { print!(\"+{}\", build); }")
		w.Writeln("    }")
	}
	w.Writeln("    println!();")
	w.Writeln("}")
	return nil
}

func rustStructMemberType(member ComponentDefinitionMember, componentdefinition ComponentDefinition) (string, error) {
	typeString, err := rustScalarType(member.Type, componentdefinition, member.Class)
	if err != nil {
		return "", err
	}
	if member.Rows > 0 || member.Columns > 0 {
		rows := member.Rows
		cols := member.Columns
		if rows == 0 {
			rows = 1
		}
		if cols == 0 {
			cols = 1
		}
		if rows == 1 && cols == 1 {
			return typeString, nil
		}
		if cols == 1 {
			return fmt.Sprintf("[%s; %d]", typeString, rows), nil
		}
		return fmt.Sprintf("[[%s; %d]; %d]", typeString, cols, rows), nil
	}
	return typeString, nil
}

func rustScalarType(paramType string, componentdefinition ComponentDefinition, paramClass string) (string, error) {
	switch paramType {
	case "uint8":
		return "u8", nil
	case "uint16":
		return "u16", nil
	case "uint32":
		return "u32", nil
	case "uint64":
		return "u64", nil
	case "int8":
		return "i8", nil
	case "int16":
		return "i16", nil
	case "int32":
		return "i32", nil
	case "int64":
		return "i64", nil
	case "bool":
		return "CBool", nil
	case "single":
		return "f32", nil
	case "double":
		return "f64", nil
	case "pointer":
		return "*mut c_void", nil
	case "string":
		return "*mut c_char", nil
	case "enum":
		return fmt.Sprintf("e%s", paramClass), nil
	case "struct":
		return fmt.Sprintf("s%s", paramClass), nil
	case "basicarray":
		return rustScalarType(paramClass, componentdefinition, "")
	case "structarray":
		return fmt.Sprintf("s%s", paramClass), nil
	case "class", "optionalclass":
		return fmt.Sprintf("%s_%s", componentdefinition.NameSpace, paramClass), nil
	case "functiontype":
		return fmt.Sprintf("%s%s", componentdefinition.NameSpace, paramClass), nil
	default:
		return "", fmt.Errorf("invalid parameter type \"%s\" for Rust", paramType)
	}
}

func rustMethodSignature(method ComponentDefinitionMethod, nameSpace string, componentdefinition ComponentDefinition, isGlobal bool, className string) (string, error) {
	params := []string{}
	if !isGlobal {
		params = append(params, fmt.Sprintf("%s_%s", nameSpace, className))
	}
	for _, p := range method.Params {
		cParams, err := generateCCPPParameter(p, className, method.MethodName, nameSpace, false)
		if err != nil {
			return "", err
		}
		for _, cParam := range cParams {
			params = append(params, rustTypeFromCParamType(cParam.ParamType, nameSpace))
		}
	}
	return fmt.Sprintf("unsafe extern \"C\" fn(%s) -> i32", strings.Join(params, ", ")), nil
}

func rustTypeFromCParamType(cType string, nameSpace string) string {
	t := strings.TrimSpace(cType)
	isConst := strings.HasPrefix(t, "const ")
	if isConst {
		t = strings.TrimSpace(strings.TrimPrefix(t, "const "))
	}
	isPtr := strings.HasSuffix(t, "*")
	if isPtr {
		t = strings.TrimSpace(strings.TrimSuffix(t, "*"))
	}

	base := ""
	switch {
	case t == "char":
		base = "c_char"
	case t == "bool":
		base = "CBool"
	case strings.HasSuffix(t, "_uint8"):
		base = "u8"
	case strings.HasSuffix(t, "_uint16"):
		base = "u16"
	case strings.HasSuffix(t, "_uint32"):
		base = "u32"
	case strings.HasSuffix(t, "_uint64"):
		base = "u64"
	case strings.HasSuffix(t, "_int8"):
		base = "i8"
	case strings.HasSuffix(t, "_int16"):
		base = "i16"
	case strings.HasSuffix(t, "_int32"):
		base = "i32"
	case strings.HasSuffix(t, "_int64"):
		base = "i64"
	case strings.HasSuffix(t, "_single"):
		base = "f32"
	case strings.HasSuffix(t, "_double"):
		base = "f64"
	case strings.HasSuffix(t, "_pvoid"):
		base = "c_void"
		isPtr = true
	case strings.HasPrefix(t, "e"+nameSpace):
		base = "e" + strings.TrimPrefix(t, "e"+nameSpace)
	case strings.HasPrefix(t, "s"+nameSpace):
		base = "s" + strings.TrimPrefix(t, "s"+nameSpace)
	default:
		base = t
	}

	if isPtr {
		if isConst {
			return "*const " + base
		}
		return "*mut " + base
	}
	return base
}

func findGlobalMethod(componentdefinition ComponentDefinition, name string) (ComponentDefinitionMethod, bool) {
	for _, method := range componentdefinition.Global.Methods {
		if method.MethodName == name {
			return method, true
		}
	}
	return ComponentDefinitionMethod{}, false
}
