/*++

Copyright (C) 2024 Autodesk Inc. (Original Author)

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

--*/

//////////////////////////////////////////////////////////////////////////////////////////////////////
// buildbindingjulia.go
// functions to generate dynamic Julia bindings of a library's API in form of explicitly loaded
// function handles.
//////////////////////////////////////////////////////////////////////////////////////////////////////

package main

import (
	"fmt"
	"log"
	"path"
	"strings"
)

// Store the julia file path
var juliaBindingFile = ""

// BuildBindingJuliaDynamic builds dynamic Julia bindings of a library's API in form of explicitly loaded
// functions handles.
func BuildBindingJuliaDynamic(componentdefinition ComponentDefinition, outputFolder string, outputFolderExample string, indentString string) error {
	forceRecreation := false

	namespace := componentdefinition.NameSpace
	libraryname := componentdefinition.LibraryName

	DynamicJuliaImpl := path.Join(outputFolder, namespace+".jl")
	juliaBindingFile = DynamicJuliaImpl
	log.Printf("Creating \"%s\"", DynamicJuliaImpl)
	dynjuliafile, err := CreateLanguageFile(DynamicJuliaImpl, indentString)
	if err != nil {
		return err
	}

	dynjuliafile.WriteJuliaLicenseHeader(componentdefinition,
		fmt.Sprintf("This is an autogenerated Julia file in order to allow an easy\n use of %s", libraryname),
		true)

	err = buildDynamicJuliaImplementation(componentdefinition, dynjuliafile)
	if err != nil {
		return err
	}

	if len(outputFolderExample) > 0 {
		DynamicJuliaExample := path.Join(outputFolderExample, namespace+"_Example"+".jl")
		if forceRecreation || !FileExists(DynamicJuliaExample) {
			log.Printf("Creating \"%s\"", DynamicJuliaExample)
			dynjuliaexamplefile, err := CreateLanguageFile(DynamicJuliaExample, indentString)
			if err != nil {
				return err
			}
			dynjuliaexamplefile.WriteJuliaLicenseHeader(componentdefinition,
				fmt.Sprintf("This is an autogenerated Julia application that demonstrates the\n usage of the Julia bindings of %s", libraryname),
				true)
			err = buildDynamicJuliaExample(componentdefinition, dynjuliaexamplefile, outputFolder)
			if err != nil {
				return err
			}
		} else {
			log.Printf("Omitting recreation of Julia example \"%s\"", DynamicJuliaExample)
		}
	}

	return nil
}

func buildDynamicJuliaImplementation(componentdefinition ComponentDefinition, w LanguageWriter) error {
	NameSpace := componentdefinition.NameSpace
	BaseName := componentdefinition.BaseName
	classMap := map[string]ComponentDefinitionClass{}
	for i := 0; i < len(componentdefinition.Classes); i++ {
		classMap[componentdefinition.Classes[i].ClassName] = componentdefinition.Classes[i]
	}

	w.Writeln("module %s", NameSpace)
	w.Writeln("using Libdl")
	w.Writeln("if !@isdefined(Cbool)")
	w.Writeln("  const Cbool = UInt8")
	w.Writeln("end")
	w.Writeln("")

	if len(componentdefinition.ImportedComponentDefinitions) > 0 {
		w.Writeln("# Injected Components")
		for _, subComponent := range componentdefinition.ImportedComponentDefinitions {
			subNameSpace := subComponent.NameSpace
			w.Writeln("include(joinpath(@__DIR__, \"..\", \"..\", \"..\", \"%s_component\", \"Bindings\", \"Julia\", \"%s.jl\"))", subNameSpace, subNameSpace)
			w.Writeln("using .%s", subNameSpace)
		}
		w.Writeln("")
	}

	w.Writeln("struct E%sException <: Exception", NameSpace)
	w.Writeln("  code::Int32")
	w.Writeln("  message::String")
	w.Writeln("end")
	w.Writeln("Base.showerror(io::IO, e::E%sException) = print(io, \"%sException \", e.code, e.message == \"\" ? \"\" : \" : \" * e.message)", NameSpace, NameSpace)
	w.Writeln("")

	w.Writeln("@enum ErrorCodes::Int32 begin")
	w.Writeln("  SUCCESS = 0")
	for _, errorDef := range componentdefinition.Errors.Errors {
		w.Writeln("  %s = %d", errorDef.Name, errorDef.Code)
	}
	w.Writeln("end")
	w.Writeln("")

	w.Writeln("const BINDING_VERSION_MAJOR = %d", majorVersion(componentdefinition.Version))
	w.Writeln("const BINDING_VERSION_MINOR = %d", minorVersion(componentdefinition.Version))
	w.Writeln("const BINDING_VERSION_MICRO = %d", microVersion(componentdefinition.Version))
	w.Writeln("")

	if len(componentdefinition.Enums) > 0 {
		w.Writeln("# Enums")
		for _, enum := range componentdefinition.Enums {
			w.Writeln("@enum e%s::Int32 begin", enum.Name)
			for _, option := range enum.Options {
				w.Writeln("  %s = %d", option.Name, option.Value)
			}
			w.Writeln("end")
		}
		w.Writeln("")
	}

	if len(componentdefinition.Structs) > 0 {
		w.Writeln("# Structs")
		for _, s := range componentdefinition.Structs {
			w.Writeln("struct s%s", s.Name)
			for _, m := range s.Members {
				memberType, err := juliaStructMemberType(m, componentdefinition)
				if err != nil {
					return err
				}
				w.Writeln("  %s::%s", m.Name, memberType)
			}
			w.Writeln("end")
		}
		w.Writeln("")
	}

	w.Writeln("abstract type Abstract%sClass end", NameSpace)
	w.Writeln("")

	w.Writeln("mutable struct Wrapper")
	w.Writeln("  lib::Ptr{Cvoid}")
	w.Writeln("  funcs::Dict{Symbol, Ptr{Cvoid}}")
	w.Writeln("  injected::Dict{String, Any}")
	w.Writeln("end")
	w.Writeln("")

	w.Writeln("function Wrapper(libraryName::Union{Nothing, AbstractString}=nothing; symbolLookupMethodAddress::Ptr{Cvoid}=C_NULL)")
	w.Writeln("  lib = C_NULL")
	w.Writeln("  funcs = Dict{Symbol, Ptr{Cvoid}}()")
	w.Writeln("  injected = Dict{String, Any}()")
	w.Writeln("  if libraryName === nothing && symbolLookupMethodAddress == C_NULL")
	w.Writeln("    libraryName = joinpath(@__DIR__, \"%s\")", BaseName)
	w.Writeln("  end")
	w.Writeln("  if libraryName !== nothing")
	w.Writeln("    libpath = String(libraryName) * \".\" * Libdl.dlext")
	w.Writeln("    try")
	w.Writeln("      lib = Libdl.dlopen(libpath)")
	w.Writeln("    catch err")
	w.Writeln("      throw(E%sException(Int32(COULDNOTLOADLIBRARY), string(err) * \" | \" * libpath))", NameSpace)
	w.Writeln("    end")
	w.Writeln("    w = Wrapper(lib, funcs, injected)")
	w.Writeln("    _loadFunctionTable!(w)")
	w.Writeln("  elseif symbolLookupMethodAddress != C_NULL")
	w.Writeln("    w = Wrapper(lib, funcs, injected)")
	w.Writeln("    _loadFunctionTableFromMethod!(w, symbolLookupMethodAddress)")
	w.Writeln("  else")
	w.Writeln("    throw(E%sException(Int32(COULDNOTLOADLIBRARY), \"Invalid library configuration\"))", NameSpace)
	w.Writeln("  end")
	w.Writeln("  _checkBinaryVersion(w)")
	w.Writeln("  return w")
	w.Writeln("end")
	w.Writeln("")

	w.Writeln("function _loadFunctionTable!(w::Wrapper)")
	for _, method := range componentdefinition.Global.Methods {
		exportName := GetCExportName(NameSpace, "Wrapper", method, true)
		w.Writeln("  w.funcs[:%s] = Libdl.dlsym(w.lib, :%s)", exportName, exportName)
	}
	for _, class := range componentdefinition.Classes {
		for _, method := range class.Methods {
			exportName := GetCExportName(NameSpace, class.ClassName, method, false)
			w.Writeln("  w.funcs[:%s] = Libdl.dlsym(w.lib, :%s)", exportName, exportName)
		}
	}
	w.Writeln("end")
	w.Writeln("")

	w.Writeln("function _loadFunctionTableFromMethod!(w::Wrapper, symbolLookupMethodAddress::Ptr{Cvoid})")
	w.Writeln("  for name in (")
	for _, method := range componentdefinition.Global.Methods {
		exportName := GetCExportName(NameSpace, "Wrapper", method, true)
		w.Writeln("    \"%s\",", exportName)
	}
	for _, class := range componentdefinition.Classes {
		for _, method := range class.Methods {
			exportName := GetCExportName(NameSpace, class.ClassName, method, false)
			w.Writeln("    \"%s\",", exportName)
		}
	}
	w.Writeln("  )")
	w.Writeln("    addr = Ref{Ptr{Cvoid}}()")
	w.Writeln("    err = ccall(symbolLookupMethodAddress, Int32, (Cstring, Ref{Ptr{Cvoid}}), name, addr)")
	w.Writeln("    if err != 0")
	w.Writeln("      throw(E%sException(Int32(COULDNOTLOADLIBRARY), string(err)))", NameSpace)
	w.Writeln("    end")
	w.Writeln("    w.funcs[Symbol(name)] = addr[]")
	w.Writeln("  end")
	w.Writeln("end")
	w.Writeln("")

	w.Writeln("function _checkBinaryVersion(w::Wrapper)")
	w.Writeln("  nMajor, nMinor, _ = %s(w)", componentdefinition.Global.VersionMethod)
	w.Writeln("  if (nMajor != BINDING_VERSION_MAJOR) || (nMinor < BINDING_VERSION_MINOR)")
	w.Writeln("    throw(E%sException(Int32(INCOMPATIBLEBINARYVERSION), \"\"))", NameSpace)
	w.Writeln("  end")
	w.Writeln("end")
	w.Writeln("")

	w.Writeln("get_handle(obj::Abstract%sClass) = getfield(obj, :handle)", NameSpace)
	w.Writeln("get_wrapper(obj::Abstract%sClass) = getfield(obj, :wrapper)", NameSpace)
	w.Writeln("")

	w.Writeln("function _checkError(w::Wrapper, instance, errorCode::Int32)")
	w.Writeln("  if errorCode != Int32(SUCCESS)")
	w.Writeln("    if instance !== nothing")
	w.Writeln("      if get_wrapper(instance) !== w")
	w.Writeln("        throw(E%sException(Int32(INVALIDCAST), \"invalid wrapper call\"))", NameSpace)
	w.Writeln("      end")
	w.Writeln("    end")
	w.Writeln("    message, _ = %s(w, instance)", componentdefinition.Global.ErrorMethod)
	w.Writeln("    throw(E%sException(errorCode, message))", NameSpace)
	w.Writeln("  end")
	w.Writeln("end")
	w.Writeln("")

	w.Writeln("function _attach_finalizer(obj)")
	w.Writeln("  finalizer(obj) do o")
	w.Writeln("    try")
	w.Writeln("      %s(get_wrapper(o), o)", componentdefinition.Global.ReleaseMethod)
	w.Writeln("    catch")
	w.Writeln("    end")
	w.Writeln("  end")
	w.Writeln("  return obj")
	w.Writeln("end")
	w.Writeln("")

	w.Writeln("function _make_object(::Type{T}, handle::Ptr{Cvoid}, w::Wrapper) where {T<:Abstract%sClass}", NameSpace)
	w.Writeln("  obj = T(handle, w)")
	w.Writeln("  return _attach_finalizer(obj)")
	w.Writeln("end")
	w.Writeln("")

	w.Writeln("# Polymorphic factory")
	w.Writeln("function _polymorphicFactory(w::Wrapper, handle::Ptr{Cvoid})")
	w.Writeln("  handle == C_NULL && return nothing")
	w.Writeln("  classTypeId = Ref{UInt64}(0)")
	w.Writeln("  err = ccall(w.funcs[:%s], Int32, (Ptr{Cvoid}, Ref{UInt64}), handle, classTypeId)",
		GetCExportName(NameSpace, componentdefinition.Global.BaseClassName, ComponentDefinitionMethod{MethodName: componentdefinition.Global.ClassTypeIdMethod}, false))
	w.Writeln("  _checkError(w, nothing, err)")
	w.Writeln("  return _objectById(w, classTypeId[], handle)")
	w.Writeln("end")
	w.Writeln("")

	w.Writeln("function _objectById(w::Wrapper, classTypeId::UInt64, handle::Ptr{Cvoid})")
	for i := 0; i < len(componentdefinition.Classes); i++ {
		classTypeId, _ := componentdefinition.Classes[i].classTypeId(NameSpace)
		if i == 0 {
			w.Writeln("  if classTypeId == 0x%016X", classTypeId)
		} else {
			w.Writeln("  elseif classTypeId == 0x%016X", classTypeId)
		}
		w.Writeln("    return _make_object(%s, handle, w)", componentdefinition.Classes[i].ClassName)
	}
	w.Writeln("  else")
	w.Writeln("    return nothing")
	w.Writeln("  end")
	w.Writeln("end")
	w.Writeln("")

	for i := 0; i < len(componentdefinition.Classes); i++ {
		class := componentdefinition.Classes[i]
		w.Writeln("mutable struct %s <: Abstract%sClass", class.ClassName, NameSpace)
		w.Writeln("  handle::Ptr{Cvoid}")
		w.Writeln("  wrapper::Wrapper")
		w.Writeln("end")
		w.Writeln("")
	}

	for j := 0; j < len(componentdefinition.Global.Methods); j++ {
		method := componentdefinition.Global.Methods[j]
		err := writeJuliaMethod(componentdefinition, method, w, NameSpace, "Wrapper", true)
		if err != nil {
			return err
		}
		w.Writeln("")
	}

	for i := 0; i < len(componentdefinition.Classes); i++ {
		class := componentdefinition.Classes[i]
		for j := 0; j < len(class.Methods); j++ {
			err := writeJuliaMethod(componentdefinition, class.Methods[j], w, NameSpace, class.ClassName, false)
			if err != nil {
				return err
			}
			w.Writeln("")
		}
		err := writeJuliaInheritedMethods(componentdefinition, classMap, class, w, NameSpace)
		if err != nil {
			return err
		}
	}

	w.Writeln("end # module %s", NameSpace)
	return nil
}

func buildDynamicJuliaExample(componentdefinition ComponentDefinition, w LanguageWriter, outputFolder string) error {
	NameSpace := componentdefinition.NameSpace
	BaseName := componentdefinition.BaseName

	w.Writeln("include(joinpath(@__DIR__, \"..\", \"..\", \"Bindings\", \"Julia\", \"%s.jl\"))", NameSpace)
	w.Writeln("using .%s", NameSpace)
	w.Writeln("")
	w.Writeln("println(\"Running %s Julia Example...\")", NameSpace)
	w.Writeln("wrapper = %s.Wrapper(\"%s\")", NameSpace, BaseName)
	versionMethod := ""
	for _, method := range componentdefinition.Global.Methods {
		if method.MethodName == "GetLibraryVersion" {
			versionMethod = method.MethodName
			break
		}
	}
	if versionMethod == "" {
		for _, method := range componentdefinition.Global.Methods {
			if method.MethodName == "GetVersion" {
				versionMethod = method.MethodName
				break
			}
		}
	}
	if versionMethod != "" {
		w.Writeln("major, minor, micro = %s.%s(wrapper)", NameSpace, versionMethod)
		w.Writeln("println(\"%s version: \" * string(major) * \".\" * string(minor) * \".\" * string(micro))", NameSpace)
	} else {
		w.Writeln("println(\"%s wrapper loaded\")", NameSpace)
	}
	return nil
}

func juliaStructMemberType(member ComponentDefinitionMember, componentdefinition ComponentDefinition) (string, error) {
	typeString, err := juliaScalarType(member.Type, componentdefinition, member.Class)
	if err != nil {
		return "", err
	}
	if member.Rows > 0 || member.Columns > 0 {
		rows := member.Rows
		cols := member.Columns
		if rows == 0 {
			rows = 1
		}
		if cols == 0 {
			cols = 1
		}
		if rows == 1 && cols == 1 {
			return typeString, nil
		}
		if cols == 1 {
			return fmt.Sprintf("NTuple{%d, %s}", rows, typeString), nil
		}
		return fmt.Sprintf("NTuple{%d, NTuple{%d, %s}}", rows, cols, typeString), nil
	}
	return typeString, nil
}

func juliaScalarType(paramType string, componentdefinition ComponentDefinition, paramClass string) (string, error) {
	switch paramType {
	case "uint8":
		return "UInt8", nil
	case "uint16":
		return "UInt16", nil
	case "uint32":
		return "UInt32", nil
	case "uint64":
		return "UInt64", nil
	case "int8":
		return "Int8", nil
	case "int16":
		return "Int16", nil
	case "int32":
		return "Int32", nil
	case "int64":
		return "Int64", nil
	case "bool":
		return "Cbool", nil
	case "single":
		return "Cfloat", nil
	case "double":
		return "Cdouble", nil
	case "pointer":
		return "Ptr{Cvoid}", nil
	case "string":
		return "Cstring", nil
	case "enum":
		return fmt.Sprintf("e%s", paramClass), nil
	case "struct":
		return fmt.Sprintf("s%s", paramClass), nil
	case "basicarray":
		return juliaScalarType(paramClass, componentdefinition, "")
	case "structarray":
		return fmt.Sprintf("s%s", paramClass), nil
	case "class", "optionalclass":
		return "Ptr{Cvoid}", nil
	default:
		return "", fmt.Errorf("invalid parameter type \"%s\" for Julia", paramType)
	}
}

func writeJuliaMethod(componentdefinition ComponentDefinition, method ComponentDefinitionMethod, w LanguageWriter, NameSpace string, ClassName string, isGlobal bool) error {
	for _, p := range method.Params {
		if p.ParamType == "functiontype" {
			return nil
		}
	}

	wrapperRef := "w"
	selfRef := "self"
	if isGlobal {
		w.Writeln("function %s(w::Wrapper%s)", method.MethodName, juliaMethodSignature(method, componentdefinition, true))
	} else {
		w.Writeln("function %s(self::%s%s)", method.MethodName, ClassName, juliaMethodSignature(method, componentdefinition, false))
	}

	preCallLines := []string{}
	postCallLines := []string{}
	returnVals := []string{}
	callArgs := []string{}
	callTypes := []string{}
	preserveFirst := []string{}
	preserveSecond := []string{}

	if !isGlobal {
		wrapperRef = "self.wrapper"
		selfRef = "self"
		callArgs = append(callArgs, "self.handle")
		callTypes = append(callTypes, "Ptr{Cvoid}")
	} else {
		selfRef = "nothing"
	}

	needsSecondCall := false

	for _, param := range method.Params {
		switch param.ParamPass {
		case "in":
			argName := param.ParamName
			switch param.ParamType {
			case "struct":
				refName := "p" + param.ParamName
				preCallLines = append(preCallLines, fmt.Sprintf("  %s = Ref{%s}(%s)", refName, juliaTypeName(param, componentdefinition), argName))
				callArgs = append(callArgs, refName)
				callTypes = append(callTypes, fmt.Sprintf("Ref{%s}", juliaTypeName(param, componentdefinition)))
			case "class":
				callArgs = append(callArgs, fmt.Sprintf("%s.handle", argName))
				callTypes = append(callTypes, "Ptr{Cvoid}")
			case "optionalclass":
				handleName := "p" + param.ParamName
				preCallLines = append(preCallLines, fmt.Sprintf("  %s = (%s === nothing) ? C_NULL : %s.handle", handleName, argName, argName))
				callArgs = append(callArgs, handleName)
				callTypes = append(callTypes, "Ptr{Cvoid}")
			case "basicarray", "structarray":
				elemType := juliaArrayElementType(param, componentdefinition)
				countName := "n" + param.ParamName + "Count"
				ptrName := "p" + param.ParamName + "Buffer"
				preCallLines = append(preCallLines, fmt.Sprintf("  %s = UInt64(length(%s))", countName, argName))
				preCallLines = append(preCallLines, fmt.Sprintf("  %s = length(%s) == 0 ? Ptr{%s}(C_NULL) : pointer(%s)", ptrName, argName, elemType, argName))
				callArgs = append(callArgs, countName, ptrName)
				callTypes = append(callTypes, "UInt64", fmt.Sprintf("Ptr{%s}", elemType))
				preserveFirst = append(preserveFirst, argName)
			default:
				callArgs = append(callArgs, argName)
				callTypes = append(callTypes, juliaTypeName(param, componentdefinition))
				if param.ParamType == "string" {
					preserveFirst = append(preserveFirst, argName)
				}
			}

		case "out", "return":
			outName := "p" + param.ParamName
			switch param.ParamType {
			case "string":
				needsSecondCall = true
				bufSize := "n" + param.ParamName + "BufferSize"
				needed := "n" + param.ParamName + "Needed"
				buf := "p" + param.ParamName + "Buffer"
				preCallLines = append(preCallLines, fmt.Sprintf("  %s = UInt64(0)", bufSize))
				preCallLines = append(preCallLines, fmt.Sprintf("  %s = Ref{UInt64}(0)", needed))
				preCallLines = append(preCallLines, fmt.Sprintf("  %s = Ptr{Cchar}(C_NULL)", buf))
				callArgs = append(callArgs, bufSize, needed, buf)
				callTypes = append(callTypes, "UInt64", "Ref{UInt64}", "Ptr{Cchar}")
				postCallLines = append(postCallLines, fmt.Sprintf("  %s = Array{UInt8}(undef, Int(%s[]))", buf, needed))
				postCallLines = append(postCallLines, fmt.Sprintf("  %s = UInt64(length(%s))", bufSize, buf))
				postCallLines = append(postCallLines, fmt.Sprintf("  %s_ptr = pointer(%s)", buf, buf))
				returnVals = append(returnVals, fmt.Sprintf("unsafe_string(%s_ptr)", buf))
				preserveSecond = append(preserveSecond, buf)
			case "basicarray", "structarray":
				needsSecondCall = true
				elemType := juliaArrayElementType(param, componentdefinition)
				countName := "n" + param.ParamName + "Count"
				needed := "n" + param.ParamName + "Needed"
				buf := "p" + param.ParamName + "Buffer"
				preCallLines = append(preCallLines, fmt.Sprintf("  %s = UInt64(0)", countName))
				preCallLines = append(preCallLines, fmt.Sprintf("  %s = Ref{UInt64}(0)", needed))
				preCallLines = append(preCallLines, fmt.Sprintf("  %s = Ptr{%s}(C_NULL)", buf, elemType))
				callArgs = append(callArgs, countName, needed, buf)
				callTypes = append(callTypes, "UInt64", "Ref{UInt64}", fmt.Sprintf("Ptr{%s}", elemType))
				postCallLines = append(postCallLines, fmt.Sprintf("  %s = Array{%s}(undef, Int(%s[]))", buf, elemType, needed))
				postCallLines = append(postCallLines, fmt.Sprintf("  %s = UInt64(length(%s))", countName, buf))
				postCallLines = append(postCallLines, fmt.Sprintf("  %s_ptr = pointer(%s)", buf, buf))
				returnVals = append(returnVals, buf)
				preserveSecond = append(preserveSecond, buf)
			case "struct":
				preCallLines = append(preCallLines, fmt.Sprintf("  %s = Ref{%s}()", outName, juliaTypeName(param, componentdefinition)))
				callArgs = append(callArgs, outName)
				callTypes = append(callTypes, fmt.Sprintf("Ref{%s}", juliaTypeName(param, componentdefinition)))
				returnVals = append(returnVals, fmt.Sprintf("%s[]", outName))
			case "enum":
				preCallLines = append(preCallLines, fmt.Sprintf("  %s = Ref{Int32}(0)", outName))
				callArgs = append(callArgs, outName)
				callTypes = append(callTypes, "Ref{Int32}")
				returnVals = append(returnVals, fmt.Sprintf("%s(%s[])", juliaTypeName(param, componentdefinition), outName))
			case "class", "optionalclass":
				if param.ParamPass == "out" && param.ParamType == "optionalclass" {
					preCallLines = append(preCallLines, fmt.Sprintf("  %s = Ref{Ptr{Cvoid}}(%s === nothing ? C_NULL : %s.handle)", outName, param.ParamName, param.ParamName))
				} else {
					preCallLines = append(preCallLines, fmt.Sprintf("  %s = Ref{Ptr{Cvoid}}(C_NULL)", outName))
				}
				callArgs = append(callArgs, outName)
				callTypes = append(callTypes, "Ref{Ptr{Cvoid}}")
				returnVals = append(returnVals, fmt.Sprintf("_polymorphicFactory(%s, %s[])", wrapperRef, outName))
			default:
				preCallLines = append(preCallLines, fmt.Sprintf("  %s = Ref{%s}()", outName, juliaTypeName(param, componentdefinition)))
				callArgs = append(callArgs, outName)
				callTypes = append(callTypes, fmt.Sprintf("Ref{%s}", juliaTypeName(param, componentdefinition)))
				if param.ParamType == "bool" {
					returnVals = append(returnVals, fmt.Sprintf("%s[] != 0", outName))
				} else {
					returnVals = append(returnVals, fmt.Sprintf("%s[]", outName))
				}
			}
		}
	}

	for _, line := range preCallLines {
		w.Writeln(line)
	}

	exportName := GetCExportName(NameSpace, ClassName, method, isGlobal)
	callTypesString := juliaTypeTuple(callTypes)
	callArgsString := strings.Join(callArgs, ", ")
	if len(preserveFirst) > 0 {
		w.Writeln("  GC.@preserve %s begin", strings.Join(preserveFirst, " "))
		if callArgsString == "" {
			w.Writeln("    err = ccall(%s.funcs[:%s], Int32, (%s))", wrapperRef, exportName, callTypesString)
		} else {
			w.Writeln("    err = ccall(%s.funcs[:%s], Int32, (%s), %s)", wrapperRef, exportName, callTypesString, callArgsString)
		}
		w.Writeln("  end")
	} else {
		if callArgsString == "" {
			w.Writeln("  err = ccall(%s.funcs[:%s], Int32, (%s))", wrapperRef, exportName, callTypesString)
		} else {
			w.Writeln("  err = ccall(%s.funcs[:%s], Int32, (%s), %s)", wrapperRef, exportName, callTypesString, callArgsString)
		}
	}
	w.Writeln("  _checkError(%s, %s, err)", wrapperRef, selfRef)

	if needsSecondCall {
		for _, line := range postCallLines {
			w.Writeln(line)
		}
		secondCallArgs := []string{}
		for _, arg := range callArgs {
			if strings.HasPrefix(arg, "p") && strings.HasSuffix(arg, "Buffer") {
				secondCallArgs = append(secondCallArgs, arg+"_ptr")
			} else {
				secondCallArgs = append(secondCallArgs, arg)
			}
		}
		secondArgsString := strings.Join(secondCallArgs, ", ")
		if len(preserveSecond) > 0 {
			w.Writeln("  GC.@preserve %s begin", strings.Join(preserveSecond, " "))
			if secondArgsString == "" {
				w.Writeln("    err = ccall(%s.funcs[:%s], Int32, (%s))", wrapperRef, exportName, callTypesString)
			} else {
				w.Writeln("    err = ccall(%s.funcs[:%s], Int32, (%s), %s)", wrapperRef, exportName, callTypesString, secondArgsString)
			}
			w.Writeln("  end")
		} else {
			if secondArgsString == "" {
				w.Writeln("  err = ccall(%s.funcs[:%s], Int32, (%s))", wrapperRef, exportName, callTypesString)
			} else {
				w.Writeln("  err = ccall(%s.funcs[:%s], Int32, (%s), %s)", wrapperRef, exportName, callTypesString, secondArgsString)
			}
		}
		w.Writeln("  _checkError(%s, %s, err)", wrapperRef, selfRef)
	}

	if len(returnVals) > 0 {
		w.Writeln("  return %s", strings.Join(returnVals, ", "))
	}

	w.Writeln("end")
	return nil
}

func juliaMethodSignature(method ComponentDefinitionMethod, componentdefinition ComponentDefinition, isGlobal bool) string {
	parts := []string{}
	for _, p := range method.Params {
		if p.ParamPass == "in" {
			parts = append(parts, fmt.Sprintf(", %s::%s", p.ParamName, juliaParamType(p, componentdefinition)))
		}
		if p.ParamPass == "out" && p.ParamType == "optionalclass" {
			parts = append(parts, fmt.Sprintf(", %s::Union{%s, Nothing}=nothing", p.ParamName, p.ParamClass))
		}
	}
	if isGlobal {
		return strings.Join(parts, "")
	}
	return strings.Join(parts, "")
}

func juliaTypeTuple(types []string) string {
	if len(types) == 0 {
		return ""
	}
	if len(types) == 1 {
		return types[0] + ","
	}
	return strings.Join(types, ", ")
}

func writeJuliaInheritedMethods(componentdefinition ComponentDefinition, classMap map[string]ComponentDefinitionClass, class ComponentDefinitionClass, w LanguageWriter, NameSpace string) error {
	if componentdefinition.isBaseClass(class) {
		return nil
	}
	ownMethods := map[string]bool{}
	for _, m := range class.Methods {
		ownMethods[m.MethodName] = true
	}

	parentName := class.ParentClass
	if parentName == "" {
		parentName = componentdefinition.Global.BaseClassName
	}
	for parentName != "" {
		parentClass, ok := classMap[parentName]
		if !ok {
			break
		}
		for _, m := range parentClass.Methods {
			if ownMethods[m.MethodName] {
				continue
			}
			if hasFunctionTypeParam(m) {
				continue
			}
			writeJuliaForwardMethod(w, NameSpace, class.ClassName, parentClass.ClassName, m, componentdefinition)
			w.Writeln("")
		}
		parentName = parentClass.ParentClass
		if parentName == "" && !componentdefinition.isBaseClass(parentClass) {
			parentName = componentdefinition.Global.BaseClassName
		}
	}
	return nil
}

func hasFunctionTypeParam(method ComponentDefinitionMethod) bool {
	for _, p := range method.Params {
		if p.ParamType == "functiontype" {
			return true
		}
	}
	return false
}

func writeJuliaForwardMethod(w LanguageWriter, NameSpace string, childClass string, parentClass string, method ComponentDefinitionMethod, componentdefinition ComponentDefinition) {
	signatureParts := []string{}
	argNames := []string{}
	for _, p := range method.Params {
		if p.ParamPass == "in" {
			signatureParts = append(signatureParts, fmt.Sprintf(", %s::%s", p.ParamName, juliaParamType(p, componentdefinition)))
			argNames = append(argNames, p.ParamName)
		}
		if p.ParamPass == "out" && p.ParamType == "optionalclass" {
			signatureParts = append(signatureParts, fmt.Sprintf(", %s::Union{%s, Nothing}=nothing", p.ParamName, p.ParamClass))
			argNames = append(argNames, p.ParamName)
		}
	}
	w.Writeln("function %s(self::%s%s)", method.MethodName, childClass, strings.Join(signatureParts, ""))
	parentCtor := fmt.Sprintf("%s(self.handle, self.wrapper)", parentClass)
	if len(argNames) > 0 {
		w.Writeln("  return %s(%s, %s)", method.MethodName, parentCtor, strings.Join(argNames, ", "))
	} else {
		w.Writeln("  return %s(%s)", method.MethodName, parentCtor)
	}
	w.Writeln("end")
}

func juliaParamType(param ComponentDefinitionParam, componentdefinition ComponentDefinition) string {
	switch param.ParamType {
	case "string":
		return "AbstractString"
	case "basicarray", "structarray":
		return fmt.Sprintf("Array{%s, 1}", juliaArrayElementType(param, componentdefinition))
	case "class":
		return param.ParamClass
	case "optionalclass":
		return fmt.Sprintf("Union{%s, Nothing}", param.ParamClass)
	default:
		return juliaTypeName(param, componentdefinition)
	}
}

func juliaArrayElementType(param ComponentDefinitionParam, componentdefinition ComponentDefinition) string {
	elemType, err := juliaScalarType(param.ParamType, componentdefinition, param.ParamClass)
	if err != nil {
		return "Cvoid"
	}
	if param.ParamType == "basicarray" {
		elemType, _ = juliaScalarType(param.ParamClass, componentdefinition, "")
	}
	return elemType
}

func juliaTypeName(param ComponentDefinitionParam, componentdefinition ComponentDefinition) string {
	t, err := juliaScalarType(param.ParamType, componentdefinition, param.ParamClass)
	if err != nil {
		return "Cvoid"
	}
	return t
}
